### PR TITLE
Strings and Lists Completed

### PR DESCRIPTION
**Pull request by nana-beep**

### CODE REVIEW

**Comment by barbarer** [comment]
Please fix the conflicts first.

**Comment by nana-beep** [comment]
Dear Professor Ericson,

May I receieve clarifications on how to fix the conflicts?

Thank you.


Best regards,
Jina

**Comment by barbarer** [comment]
I went ahead and merged them.  I had made changes to the list mixed up code and so had you.  That is why it is important that you do git fetch upstream before you commit and push.  You will be notified if there are any conflicts when you do that.  You can then edit the file and it will show you how they differ.  You save the changes you want and then save the file.

**Comment by nana-beep** [comment]
Dear Professor Ericson,

I understand, thank you so much. I'll make sure to do that next time.


Best regards,
Jina Kim

**Pull request merged**
